In [1]:
import PySimpleGUI as sg
from random import randint
import numpy as np
from scipy import signal
MAX_ROWS = MAX_COL = 10
board = [[randint(0,1) for j in range(MAX_COL)] for i in range(MAX_ROWS)]
board = np.zeros(MAX_ROWS*MAX_COL).astype(np.int)
idx = np.random.choice(len(board), 3, replace=False) # 爆弾をランダムに3箇所設置
board[idx] = 1
board = board.reshape(MAX_ROWS, MAX_COL).tolist()
filter = np.array([ # 二次元畳み込みで爆弾の数をカウント
    [1,1,1],
    [1,0,1],
    [1,1,1]
    ])
counter = signal.convolve2d(board, filter, 'full') # 畳み込みとサイズが大きくなるので、
board = counter[1:-1,1:-1] - board # スライスする。ここでboardを引くことで、爆弾マスは-1になる
print (board)
board = board.tolist()
layout =  [[sg.Button('?', size=(4, 2), key=(i,j), pad=(0,0)) for j in range(MAX_COL)] for i in range(MAX_ROWS)]
window = sg.Window('Minesweeper', layout)
while True:
    event, values = window.read()
    print (event,values)
    if event in (None, 'Exit'):
        break
    select = sg.popup('マスに対する操作を選択してください',custom_text=('open', 'flag'),title='')
    print('select', select)
    if select is 'open':
        window[event].update(board[event[0]][event[1]], button_color=('white','black'))
        if board[event[0]][event[1]]==-1:
            sg.popup("You Lose")
            break
    elif select is 'flag':
        state = window[event].GetText()
        if state == '?':
            window[event].update('F', button_color=('red',None))
        elif state == 'F':
            window[event].update('?', button_color=('white',None))
window.close()


[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  1  1  0  0]
 [ 0  0  0  0  0  1 -1  1  0  0]
 [ 0  0  0  0  0  1  1  2  1  1]
 [ 0  0  0  0  0  0  0  1 -1  1]
 [ 0  1  1  1  0  0  0  1  1  1]
 [ 0  1 -1  1  0  0  0  0  0  0]
 [ 0  1  1  1  0  0  0  0  0  0]]
(5, 1) {}
select open
(8, 2) {}
select open


# 参考文献
- [PySimpleGUIでマインスイーパ](https://kakedashi-engineer.appspot.com/2020/04/03/simple-gui/)